# Generated by Django 5.1.6 on 2025-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_donat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donat',
            name='image',
            field=models.ImageField(upload_to='donats/', verbose_name='Картинка'),
        ),
    ]
