# Generated by Django 5.1.6 on 2025-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_coment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donat',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
